
name: Android Release CI

on:
  push:
    tags:
      - 'v*.*.*'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode and create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
        run: echo "${{ secrets.GEONAMES_USERNAME }}" > local.properties
        run: echo "${{ secrets.GOOGLE_SERVER_CLIENT_ID }}" >> local.properties
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/DriveList-${{ github.ref_name }}.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: app/build/outputs/apk/release/DriveList-${{ github.ref_name }}.apk